### PR TITLE
Upgrade for PureScript 0.15

### PR DESCRIPTION
**Pull request by thomashoneyman**
Hey @hdgarrood 👋 

This PR updates the library for compatibility with PureScript 0.15. It's required for downstream libraries like `spec` (see: https://github.com/purescript-spec/purescript-spec/pull/120). All dependencies have already had their updates, so you can make a new release as soon as this merges.

### CODE REVIEW

**Comment by hdgarrood** [comment]
Thanks! Looks like it’s failing due to an outdated version of Node in CI - do you think  you might be able to resolve that?

**Comment by thomashoneyman** [comment]
@hdgarrood I bumped the node version but it needs approval to run

**Comment by hdgarrood** [comment]
Huh, I assumed that having approved it previously meant that I wouldn't need to approve it again, although I suppose it makes sense that changing the github actions yaml should require another approval.

**Comment by hdgarrood** [comment]
Thank you!

**Comment by hdgarrood** [comment]
Published as v7.0.0

**Pull request merged**
