### PR TITLE
updates for 0.12

### PR DESCRIPTION
**Pull request by justinwoo**

### CODE REVIEW

**Comment by hdgarrood** [comment]
I’d actually prefer to wait until there are real releases of these. Does that make things awkward?

**Comment by justinwoo** [comment]
This should go in a `#compiler/0.12` branch for now

**Comment by hdgarrood** [comment]
Ok, I guess that's easy enough to do.

**Comment by hdgarrood** [comment]
Merged in at https://github.com/hdgarrood/purescript-ansi/commit/633b6fd8e994a288b884af7efea9f29b0522b093

**Pull request closed without merging**
