### PR TITLE
Add CI via GH Actions

### PR DESCRIPTION
**Pull request by fsoikin**
You mentioned you'd like CI on this library in #12, so here it is. Let me know if this is satisfactory.

### CODE REVIEW

**Comment by hdgarrood** [comment]
Thank you! ❤️

This looks reasonable to me. Do you know why it isn’t running?

**Comment by fsoikin** [comment]
As far as I understand, it's not running right now because it's not yet merged. It makes sense to me: if it did run, then anybody would be able to create a pull request and drain your GH Actions minutes, and you could do nothing about it.

I did run it on my own repo ([see here](https://github.com/fsoikin/purescript-ansi/actions/runs/608950284)) before creating a pull request. I did it by temporarily commenting out `branches: [master]` under `on -> push`.

**Comment by fsoikin** [comment]
Oh great, looks like it's running now! 
Mind if I open a dummy PR just to see if it will run on PRs?

**Comment by hdgarrood** [comment]
Sure, go ahead :)

**Pull request merged**
